[tool.poetry]
name = "learning-mecab-py"
version = "0.1.0"
description = "ğŸ›–ğŸ›–ğŸ›– MeCabã‚’ä½¿ã£ã¦å½¢æ…‹ç´ è§£æã‚’è¡Œã†Pythonãƒ—ãƒ­ã‚°ãƒ©ãƒ ã§ã™ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "learning_mecab"}]

[tool.poetry.dependencies]
python = "3.11.x"
mecab-python3 = "^1.0.8"
unidic = "^1.1.0"
fastapi = "^0.108.0"
uvicorn = {extras = ["standard"], version = "^0.25.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
